name: babysitterapp
description: "A collaborative babysitter mobile app for the final project in it415."

publish_to: 'none' 

version: 1.0.0+1

environment:
 sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0
  flutter_animate: ^4.3.0
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.8
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 
    
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/images/placeholder_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/placeholder_logo.png"
  adaptive_icon_background: "#ffffff"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/placeholder_logo.png"
