name: babysitterapp
description: "A collaborative babysitter mobile app for the final project in it415."

publish_to: 'none' 

version: 1.0.13+1

environment:
 sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0
  flutter_animate: ^4.3.0
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  hugeicons: ^0.0.7
  fluentui_system_icons: ^1.1.257
  flutter_dotenv: ^5.1.0
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.4.2
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.8
  build_runner: ^2.4.6
  husky: ^0.1.7
  test: ^1.25.7


# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/images/placeholder_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/placeholder_logo.png"
  adaptive_icon_background: "#ffffff"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/placeholder_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env 

    
fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand_Bold_Oblique.otf
        - asset: assets/fonts/Quicksand_Bold.otf
        - weight: 700
    - family: Quicksan_Book
      fonts:
        - asset: assets/fonts/Quicksand_Book_Oblique.otf
        - asset: assets/fonts/Quicksand_Book.otf
    - family: Nexa-ExtraLight
      fonts:
        - asset: assets/fonts/Nexa-ExtraLight.ttf
        - weight: 700
    - family: Nexa-Heavy
      fonts:
        - asset: assets/fonts/Nexa-Heavy.ttf
        - weight: 900
        
             
             
