name: Auto Create Pull Request

on:
  push:
    branches:
      - Escopalao_Group
      - Lara_Group
      - Macas_Group
      - Manipon_Group
      - Millan_Group
      - Ruña_Group

jobs:
  create_and_handle_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto PR from ${{ github.ref_name }}
          title: "Auto PR: Merge ${{ github.ref_name }} into main"
          body: |
            This is an automated pull request created from a push to the ${{ github.ref_name }} branch.
            Please review the changes and merge if appropriate.
            If not reviewed within 24 hours, this PR will be automatically merged.
          branch: auto-pr-${{ github.ref_name }}
          base: main
          delete-branch: true
          labels: |
            automated pr
            review required
          draft: false

      - name: Print PR Details
        if: steps.create_pr.outputs.pull-request-number
        run: |
          echo "Pull Request Number - ${{ steps.create_pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"

      - name: No PR Created
        if: steps.create_pr.outputs.pull-request-number == ''
        run: echo "No pull request was created"

      - name: Sleep for 24 hours
        run: sleep 86400
        if: steps.create_pr.outputs.pull-request-number

      - name: Check PR status and merge if not reviewed
        if: steps.create_pr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
        run: |
          PR_STATE=$(gh pr view $PR_NUMBER --json state -q .state)
          if [ "$PR_STATE" = "OPEN" ]; then
            REVIEW_DECISION=$(gh pr view $PR_NUMBER --json reviewDecision -q .reviewDecision)
            if [ "$REVIEW_DECISION" = "null" ] || [ "$REVIEW_DECISION" = "REVIEW_REQUIRED" ]; then
              gh pr merge $PR_NUMBER --merge --admin
              echo "Pull request #$PR_NUMBER auto-merged after 24 hours without review."
            else
              echo "Pull request #$PR_NUMBER has been reviewed. No auto-merge performed."
              exit 0
            fi
          else
            echo "Pull request #$PR_NUMBER is not open. No action taken."
            exit 0
          fi

      - name: Sync changes to main
        if: success()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch origin
          git checkout main
          git merge origin/${{ github.ref_name }} -X theirs
          git push origin main
