name: Auto Create Pull Request

on:
  push:
    branches:
      - Escopalao_Group
      - Lara_Group
      - Macas_Group
      - Manipon_Group
      - Millan_Group
      - Ruña_Group

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto PR from ${{ github.ref_name }}
          title: "Auto PR: Merge ${{ github.ref_name }} into main"
          body: |
            This is an automated pull request created from a push to the ${{ github.ref_name }} branch.
            Please review the changes and merge if appropriate.
          branch: auto-pr-${{ github.ref_name }}
          base: main
