name: Auto Create Pull Request

on:
  push:
    branches:
      - Escopalao_Group
      - Lara_Group
      - Macas_Group
      - Manipon_Group
      - Millan_Group
      - Ruña_Group

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto PR from ${{ github.ref_name }}
          title: "Auto PR: Merge ${{ github.ref_name }} into main"
          body: |
            This is an automated pull request created from a push to the ${{ github.ref_name }} branch.
            Please review the changes and merge if appropriate.
          branch: auto-pr-${{ github.ref_name }}
          base: main
          delete-branch: true
          labels: |
            automated pr
            review required

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: No PR Created
        if: ${{ !steps.cpr.outputs.pull-request-number }}
        run: echo "No pull request was created"
