name: Trigger Branch Updates
on:
  pull_request:
    types:
      - closed

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Trigger Update All Branches workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-branch-update
